name: chitti
description: "Your last minute exam preparation buddy"
publish_to: 'none' 
version: 1.2.3+15

environment:
  sdk: ^3.7.0-267.0.dev

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.3.0
  shared_preferences: ^2.5.2
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  collection: ^1.19.0
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  pdfrx: 1.2.0
  video_player: 2.9.3
  razorpay_flutter: ^1.4.0
  no_screenshot: ^0.3.2-beta.3
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.1
  fvp: 0.31.0
  firebase_messaging: ^15.2.5
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.8

msix_config:
  display_name: CHITTI
  publisher_display_name: Chitti
  identity_name: dev.theananta.chitti
  msix_version: 1.0.0.0
  logo_path: D:\Learning\Projects\the-ananta\CHITTI\chitti_ghost_orange.png
  capabilities: internetClient
  certificate_path: C:\Users\jayad\CHITTICERTIFICATE.pfx
  certificate_password: Girish@092005

flutter:
  uses-material-design: true
  assets:
    - assets/images/